//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MapWing.rc
//
#define IDD_ABOUTBOX                    100
#define IDS_OPENFILE_REMIND             101
#define IDC_TREE_LAYER                  102
#define IDB_SPLASH                      103
#define IDR_MAINFRAME                   128
#define IDR_MAPWINTYPE                  129
#define IDD_CHANGEFORMATDLG1            130
#define IDC_ZOOMIN                      131
#define IDC_ZOOMOUT                     132
#define IDC_PAN2                        133
#define IDC_PAN1                        134
#define IDD_INFODISPLAY                 135
#define IDB_BITMAP1                     136
#define IDD_LAYERCHOOSE                 137
#define IDD_POINTSYM_DLG                138
#define IDD_LINESYM_DLG                 139
#define IDD_GONSYM_DLG                  140
#define IDD_ANNOSYM_DLG                 141
#define IDD_HawkDlg                     142
#define IDR_MENUTREE                    143
#define IDR_MAP                         144
#define IDR_EYE                         145
#define IDB_BITMAP2                     146
#define IDB_BITMAP3                     147
#define IDB_TOOLBARCOLOR                148
#define IDB_TOOLBARDISABLE              149
#define IDB_TOOLBARHOT                  150
#define IDR_TOOLBAR1                    151
#define IDR_TOOLBAR                     153
#define IDB_TOOLBAR1COLOR               155
#define IDB_TOOLBAR1DISABLE             156
#define IDB_TOOLBAR1HOT                 157
#define IDC_CURSOR1                     163
#define IDC_CURSOR2                     164
#define IDB_BITMAP4                     167
#define IDB_BITMAP5                     168
#define IDB_BITMAP6                     169
#define IDB_BITMAP7                     170
#define IDB_BITMAP8                     171
#define IDB_BITMAP9                     172
#define IDB_BITMAP10                    173
#define IDB_BITMAP11                    174
#define IDI_ICON2                       176
#define IDI_ICON3                       177
#define IDB_BITMAP12                    178
#define IDI_ICON1                       179
#define IDI_ICON4                       180
#define IDI_ICON5                       181
#define IDI_ICON6                       182
#define IDI_ICON7                       183
#define IDB_BITMAP13                    185
#define IDC_EDIT1                       1000
#define IDC_EDIT2                       1001
#define IDC_SOURCE                      1002
#define IDC_GOAL                        1003
#define IDC_LAYER_INFO                  1005
#define IDC_POINT_G                     1006
#define IDC_POINT_B                     1007
#define IDC_PT1                         1008
#define IDC_PT2                         1009
#define IDC_PT3                         1010
#define IDC_POINT_RADIUS                1013
#define IDC_SPIN1                       1014
#define IDC_POINT_R                     1015
#define IDC_RADIO1                      1016
#define IDC_LT1                         1016
#define IDC_RADIO2                      1017
#define IDC_LT2                         1017
#define IDC_RADIO3                      1018
#define IDC_LT3                         1018
#define IDC_RADIO4                      1019
#define IDC_LT4                         1019
#define IDC_RADIO5                      1020
#define IDC_LT5                         1020
#define IDC_EDIT3                       1021
#define IDC_TEXTB                       1021
#define IDC_EDIT4                       1022
#define IDC_LINE_B                      1022
#define IDC_FILL_G                      1024
#define IDC_FILL_B                      1025
#define IDC_BOND_R                      1026
#define IDC_BOND_G                      1027
#define IDC_BOND_B                      1028
#define IDC_FILL_R                      1029
#define IDC_COMBO1                      1030
#define IDC_LINE_WIDTH                  1030
#define IDC_LINE_R                      1031
#define IDC_LINE_G                      1032
#define IDC_TEXTR                       1033
#define IDC_TEXTG                       1034
#define IDC_CHOOSEPOINTCOLOR            1035
#define IDC_TEXTFONT_LIST               1036
#define IDC_CHANGELINECOLOR             1036
#define IDC_CHANGEFILLCOLOR             1038
#define IDC_CHANGEANNOCOLOR             1039
#define ID_CHANGEFORMAT                 32771
#define ID_FULLWINDS                    32772
#define ID_ZOOMIN                       32773
#define ID_ZOOMOUT                      32774
#define ID_PAN                          32775
#define ID_ZOOMINPOINT                  32776
#define ID_ZOOMOUTPOINT                 32777
#define ID_MEASUREDISTANCE              32778
#define ID_MEASUREAREA                  32779
#define ID_LAYERSELECT                  32780
#define ID_BMPSAVE                      32781
#define ID_SHOW_LAYER                   32782
#define ID_SHOW_HawkeyeDLG              32783
#define ID_FILESAVE                     32784
#define ID_CUT                          32788
#define ID_REFRESH                      32790
#define ID_PRINT                        32791
#define ID_INDICATOR_INSERT             61446
#define ID_INDICATOR_TIME               61447
#define ID_INDICATOR_MOUSE              61448
#define ID_MOVEWEL                      61449

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        191
#define _APS_NEXT_COMMAND_VALUE         32806
#define _APS_NEXT_CONTROL_VALUE         1040
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
